apiVersion: v1
kind: ConfigMap
metadata:
  name: practice-web-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      # restore proper content-types (html, js, css, etc.)
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      # no directory listing
      autoindex off;

      # canonicalize /practice (optional)
      location = /practice { return 301 /practice/; }

      # Docsify SPA fallback under /practice/
      # NOTE: do NOT use "$uri/" here
      location /practice/ {
        try_files $uri /index.html;
      }

      # Also serve the SPA for bare "/"
      location / {
        try_files $uri /index.html;
      }
    }
