apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # Important: empty storageClassName to bind to a classless static PV
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs
