apiVersion: v1
kind: Pod
metadata:
  name: nfs-static-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["/bin/sh","-c"]
      args:
        - |
          echo "hello-from-static-pv" > /work/hello.txt && \
          tail -f /dev/null
      volumeMounts:
        - name: work
          mountPath: /work
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: nfs-static-pvc
